@startuml
card "<size:42><&terminal></size> zwalletcli" as cli

folder filesystem {
    file "\~/.zcn/config.yaml" as config
    file "\~/.zcn/wallet.json" as wallet
}

cloud "0chain network" {

  node miners [
       Miner1
       ===
       Miner2
       ===
       ...
  ]

  node sharders [
       Sharder1
       ===
       Sharder2
       ===
       ...
  ]

  node "0dns" as 0dns
}

cli ---> config: start with
cli ---> wallet: read
cli ---> 0dns: discover nodes
cli ---> miners: send txns
cli ---> sharders: verify txns, get data

note bottom of config: required zwallet config
note bottom of wallet: contains secret key
note bottom of miners: processes transactions
note bottom of sharders: holds blockchain data
note bottom of 0dns: serves the latest miner and sharder node details


@enduml