@startuml
participant "<size:20><&terminal></size> ./zwallet mn-user-info" as cli
participant "<size:20><&file></size> \~/.zcn/wallet.json" as wallet
collections sharders

cli -> wallet: read wallet
cli -> sharders: get staked tokens of wallet from miner SC

@enduml