@startuml
participant "<size:20><&terminal></size> ./zwallet vp-delete" as cli
participant "<size:20><&file></size> \~/.zcn/wallet.json" as wallet
collections miners
collections sharders

cli -> wallet: read wallet
cli -> cli: create vesting SC delete txn for pool
cli -> miners: send txn
cli -> sharders: poll for txn confirmation

@enduml