@startuml
participant "<size:20><&terminal></size> ./zwallet vp-info" as cli
participant "<size:20><&file></size> \~/.zcn/wallet.json" as wallet
collections sharders

cli -> wallet: read wallet
cli -> sharders: get vesting pool info from vesting SC

@enduml