---
miners:
- http://cala.devc.testnet-0chain.net:7071
- http://calb.devc.testnet-0chain.net:7071
- http://vira.devc.testnet-0chain.net:7071
- http://virb.devc.testnet-0chain.net:7071
sharders:
- http://cala.devc.testnet-0chain.net:7171
- http://vira.devc.testnet-0chain.net:7171
signature_scheme: bls0chain
num_of_keys: 1
...
