---
miners:
  - http://localhost:7071
  - http://localhost:7072
  - http://localhost:7073
sharders:
  - http://localhost:7171
  - http://localhost:7172
  - http://localhost:7173
signature_scheme: ed25519
num_of_keys: 1
...
